### ISSUE TITLE
After successful authentication take me to the smartnote I was hoping to view

### ISSUE THREAD

**Issue by yflicker** [oestrich/smartnote#8]
Current behavior:
1. Assume I am not signed in
1. I navigate to a smartnote e.g. https://smartnote.dev/questions/2f3448b4-a9a8-47dd-a074-5674750fcd56
1. I click Sign In and sign in
1. I am taken to / (https://smartnote.dev/)

Desired behavior:
1. Assume I am not signed in
1. I navigate to a smartnote e.g. https://smartnote.dev/questions/2f3448b4-a9a8-47dd-a074-5674750fcd56
1. I click Sign In and sign in
1. I am taken to the URL / smartnote that I originally landed on e.g. https://smartnote.dev/questions/2f3448b4-a9a8-47dd-a074-5674750fcd56

**Comment by oestrich** [comment]
Closed with 6278a1f7bc16c4d85f99b2ac90ce38f536fd44ea
